services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    image: pushkarrr09/recipe-maker:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    command: [ "uvicorn", "main:app", "--host", "${HOST}", "--port", "${PORT}"]

    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


volumes:
  postgres_data:
